# Site settings
title: 辉夜售后
SEOTitle: 辉夜售后 | Bilibili@万象辉夜
header-img: img/home-bg.jpg
email: 2211546588@qq.com
description: "不清楚这个地方作用在哪儿 | 每日摸鱼好助手"
keyword: "My, 迷你, 小氪奇, 安装, 找回，白屏，功能"
url: "https://wxhyshop.cn" # your host, for absolute URL
baseurl: "https://wxhyshop.cn" # for example, '/blog' if your blog hosted on 'host/blog'
icpdata: "粤ICP备2025477818号-1" # your ICP data, if you have one

# Publish posts or collection documents with a future date.
future: true
gems: [jekyll-paginate]
# SNS settings
RSS: false
# weibo_username: huxpro
# zhihu_username: huxpro
github_username: WXHY2004
qqchannel_username: 585296503976495340/text/71117119
bilibili_username: 36627656
qqgroup : 1
wx_QRcode: 1 
# twitter_username: huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: hux

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "你的每日摸鱼好助手 <br> 疯狂星期四主持人<br>店铺唯一的客服喵~"
sidebar-avatar: /img/icon_wechat.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "My作者（My清清吃榴莲）", href: "https://space.bilibili.com/278537956/" },
    { title: "迷你维护作者（九亿少女的梦_小语）", href: "https://space.bilibili.com/444910916/" },
    { title: "小氪奇作者（大大怪丨下士）", href: "https://space.bilibili.com/45136342" },
    { title: "辉夜少年的研究·页游每周更新", href: "https://pd.qq.com/g/WXHYBZ1WFL/text/71117119" },
    { title: "辉夜少年的研究·手游每月更新", href: "https://pd.qq.com/g/WXHYBZ1WFL/text/520690433" },
    { title: "奥奇传说吧", href: "https://tieba.baidu.com/f?kw=%E5%A5%A5%E5%A5%87%E4%BC%A0%E8%AF%B4%E5%90%A7" },
    { title: "奥奇传说页游频道", href: "https://pd.qq.com/g/9h1iwror5i/text/1811991" },
    { title: "奥奇传说手游频道", href: "https://pd.qq.com/g/pd3396620944" },
  ]
